//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Ifcb.rc
//
#define IDD_FLUIDS                      101
#define IDD_IFCB_DIALOG                 102
#define IDD_CAMERA                      103
#define IDD_HARDWARE                    104
#define IDD_ZOOM                        105
#define IDD_TAB                         106
#define IDR_MAINFRAME                   128
#define IDD_GRAPH                       133
#define IDD_DIAGNOSTICS                 134
#define IDD_FOCUS_MIRROR                135
#define IDD_EXPERT                      136
#define IDC_PICVIEW                     1001
#define IDC_COMBO1                      1003
#define IDC_DEBAYER_COMBO               1003
#define IDC_MODE_SELECT                 1003
#define IDC_GRAPH_COMBO                 1003
#define IDC_CHECK1                      1005
#define IDC_FLUID_ACTIVE                1005
#define IDC_FAN_AUTO                    1005
#define IDC_ALIGNMENT                   1005
#define IDC_GRAPH_RUN                   1005
#define IDC_FRAMECOUNT                  1006
#define IDC_HUMID_AUTO                  1006
#define IDC_FRAMEDROPPEDCOUNT           1007
#define IDC_FRAMECOUNT2                 1007
#define IDC_SHUTTER_MIN                 1010
#define IDC_SHUTTER_MAX                 1011
#define IDC_CHECK2                      1012
#define IDC_CHECK_IMAGE_TRANSFORM       1012
#define IDC_LIVE                        1012
#define IDC_BACKFLUSH_WITH_SAMPLE       1012
#define IDC_BUTTON1                     1013
#define IDC_READBACK                    1013
#define IDC_ZOOM_BUTT                   1013
#define IDC_TRIGGER                     1013
#define IDC_SAMP_VOL_SET                1013
#define IDC_SET_POINTS                  1013
#define IDC_SMALL_R                     1013
#define IDC_BUTTON2                     1014
#define IDC_PMTA_SET                    1014
#define IDC_LARGE_R                     1014
#define IDC_DEBUBBLE_WITH_SAMPLE        1014
#define IDC_SET_YMAX                    1014
#define IDC_BUTTON3                     1015
#define IDC_PMTA_ON                     1015
#define IDC_DACS_ON                     1015
#define IDC_LARGE_L                     1015
#define IDC_BEADS_INT_SET               1015
#define IDC_PRIME_SAMPLE                1015
#define IDC_PRIME_SAMPLE_TUBE           1015
#define IDC_SET_YMAX2                   1015
#define IDC_SET_XMAX                    1015
#define IDC_BUTTON4                     1016
#define IDC_PMTB_SET                    1016
#define IDC_SMALL_L                     1016
#define IDC_SAMP_VOL_SET2               1016
#define IDC_STAIN_SAMPLE                1016
#define IDC_BUTTON5                     1017
#define IDC_PMTB_ON                     1017
#define IDC_RESET_TRIG                  1017
#define IDC_LARGE_SET                   1017
#define IDC_STAIN_SAMPLE2               1017
#define IDC_BUTTON6                     1018
#define IDC_PMTC_SET                    1018
#define IDC_SMALL_SET                   1018
#define IDC_STAIN_SAMPLE3               1018
#define IDC_BUTTON7                     1019
#define IDC_PMTC_ON                     1019
#define IDC_FORCE_TRIG_NO_CAMERA        1019
#define IDC_CLEAR                       1019
#define IDC_REPLACEFROMSEC              1019
#define IDC_BUTTON8                     1020
#define IDC_TRIG_SETA                   1020
#define IDC_STAIN_SAMPLE4               1020
#define IDC_CHECK3                      1021
#define IDC_TRIG_ON                     1021
#define IDC_TRIG_SETB                   1021
#define IDC_STAIN_SAMPLE5               1021
#define IDC_CHECK4                      1022
#define IDC_FLASH_SET                   1022
#define IDC_DEBUBBLE_WITH_SAMPLE2       1022
#define IDC_CHECK5                      1023
#define IDC_PMTA_SET3                   1023
#define IDC_PMTA_SET2                   1023
#define IDC_BUTTON9                     1024
#define IDC_FLUSH                       1024
#define IDC_FAN_SET                     1024
#define IDC_CHECK6                      1025
#define IDC_HUMID_SET                   1025
#define IDC_CHECK7                      1026
#define IDC_FILL1microinjector          1026
#define IDC_BUTTON16                    1027
#define IDC_FILL2bypassFilter           1027
#define IDC_CHECK10                     1027
#define IDC_CHECK8                      1028
#define IDC_FILL3newSheath              1028
#define IDC_CHECK11                     1028
#define IDC_BUTTON10                    1029
#define IDC_FLUIDS_INIT                 1029
#define IDC_ISOL                        1029
#define IDC_BUTTON11                    1030
#define IDC_FLUIDS_TEST                 1030
#define IDC_SPARE                       1030
#define IDC_BUTTON12                    1031
#define IDC_FANS                        1031
#define IDC_FLUIDS_TEST2                1031
#define IDC_EDIT1                       1032
#define IDC_LASER                       1032
#define IDC_BUTTON13                    1033
#define IDC_PMTB_SP                     1033
#define IDC_EDIT3                       1033
#define IDC_CHECK9                      1034
#define IDC_PMTC_SP                     1034
#define IDC_EDIT4                       1034
#define IDC_BUTTON14                    1035
#define IDC_TRIG_THRESHB                1035
#define IDC_EDIT5                       1035
#define IDC_BUTTON15                    1036
#define IDC_FLASH_SP                    1036
#define IDC_EDIT6                       1036
#define IDC_BUTTON17                    1037
#define IDC_TEMP_ADC                    1037
#define IDC_EDIT7                       1037
#define IDC_EDIT2                       1038
#define IDC_PMTA_ADC                    1038
#define IDC_TRIG_THRESHC                1038
#define IDC_EDIT_NSYRINGES              1038
#define IDC_EDIT11                      1038
#define IDC_BEADSINT                    1038
#define IDC_BUTTON18                    1039
#define IDC_PMTB_ADC                    1039
#define IDC_TRIG_SETC                   1039
#define IDC_EDIT8                       1039
#define IDC_SPIN1                       1040
#define IDC_EXPOSURE_SLIDER             1040
#define IDC_PMTC_ADC                    1040
#define IDC_PMTC_SP3                    1040
#define IDC_TRIG_THRESHD                1040
#define IDC_PMTB_SP3                    1040
#define IDC_PMTB_SP2                    1040
#define IDC_EDIT9                       1040
#define IDC_COMBO2                      1041
#define IDC_TRIG_ADC                    1041
#define IDC_PMTC_SET3                   1041
#define IDC_PMTB_SET3                   1041
#define IDC_PMTB_SET2                   1041
#define IDC_EDIT10                      1041
#define IDC_FLASH_ADC                   1042
#define IDC_TRIG_THRESHD2               1042
#define IDC_PUMP_VOLTS                  1042
#define IDC_EDIT13                      1042
#define IDC_FAN_THRESH                  1043
#define IDC_HUMID_ADC                   1044
#define IDC_EDIT15                      1044
#define IDC_TAB1                        1045
#define IDC_EDIT14                      1045
#define IDC_EDIT16                      1045
#define IDC_CAMERA                      1046
#define IDC_EDIT17                      1046
#define IDC_B_TRIGGER                   1047
#define IDC_STIRRER                     1047
#define IDC_RUN                         1048
#define IDC_PUMP1                       1048
#define IDC_LOAD_BUTTON                 1049
#define IDC_PUMP2                       1049
#define IDC_RUN2                        1049
#define IDC_TRIG_CONT                   1049
#define IDC_SAVE_BUTTON                 1050
#define IDC_FORCE_TRIG_NO_CAMERA2       1050
#define IDC_POLL_ADCS                   1050
#define IDC_BLOB_CHECK                  1051
#define IDC_FOCUS_MIRROR                1051
#define IDC_VIEW_IMAGES                 1052
#define IDC_FLASHLAMP                   1052
#define IDC_VERBOSE                     1053
#define IDC_VIEW_IMAGES2                1053
#define IDC_SAVE_ALL                    1053
#define IDC_PUMP_SET                    1053
#define IDC_FLUIDS_STOP                 1054
#define IDC_ALT_CONFIG                  1054
#define IDC_DEBUBBLE_AND_REFILL         1055
#define IDC_ALT_CFG_SET                 1055
#define IDC_SYRINGE0                    1056
#define IDC_PMTC_SP4                    1056
#define IDC_PMTC_SP2                    1056
#define IDC_RUN_SAMPLE                  1057
#define IDC_PMTC_SET4                   1057
#define IDC_PMTC_SET2                   1057
#define IDC_DRAW_F                      1058
#define IDC_DRAIN_FILTERS               1058
#define IDC_DACS_ON2                    1058
#define IDC_LASER_MOTOR                 1058
#define IDC_ADD_STAIN                   1059
#define IDC_FILL_FILTER                 1059
#define IDC_FILL_FILTERS                1059
#define IDC_TRIG_SETA2                  1059
#define IDC_SAMPLE2CONE                 1060
#define IDC_TRIG_THRESHB2               1060
#define IDC_TRIG_SETB2                  1061
#define IDC_SYRINGE1                    1061
#define IDC_TRIG_THRESHC2               1062
#define IDC_RINSE_STAIN                 1062
#define IDC_TRIG_SETC2                  1063
#define IDC_EMPTY_MIXING_CHAMBER        1063
#define IDC_FLASH_SP2                   1064
#define IDC_ACQSTARTTIMEOUT             1064
#define IDC_DEBUBBLE_AND_REFILL2        1064
#define IDC_FLASH_SET2                  1065
#define IDC_PMTA_SP                     1081
#define IDC_TRIG_THRESHA                1082
#define IDC_PMTA_SP3                    1083
#define IDC_PMTA_SP2                    1083
#define IDC_TRIG_THRESHA2               1084
#define IDC_CAMERA_LABEL                1086
#define IDC_LASER_LABEL                 1087
#define IDC_ISOL_LABEL                  1090
#define IDC_SPARE_LABEL                 1091
#define IDC_FAN_LABEL                   1092
#define IDC_FAN_THRESH_LABEL            1093
#define IDC_HUMID_THRESH_LABEL          1094
#define IDC_CAMERA_LABEL2               1095
#define IDC_FLASHLAMP_LABEL             1095
#define IDC_ZOOMPIC                     1096
#define IDC_FILL1microinjector_LABEL    1097
#define IDC_FILL2bypassFilter_LABEL     1098
#define IDC_FILL3newSheath_LABEL        1099
#define IDC_VALVE_GROUP                 1100
#define IDC_STIRRER_LABEL               1101
#define IDC_PUMP1_LABEL                 1102
#define IDC_PUMP2_LABEL                 1103
#define IDC_SWITCH_GROUP                1104
#define IDC_GRAPH                       1105
#define IDC_GRAPH_POINTS                1106
#define IDC_LARGE_STEP                  1107
#define IDC_GRAPH_YMAX                  1107
#define IDC_SMALL_STEP                  1108
#define IDC_GRAPH_XMAX                  1108
#define IDC_GRAPH_YMAX2                 1108
#define IDC_SMALL_STEP2                 1109
#define IDC_POSITION                    1109
#define IDC_TRIG_ENA                    1109
#define IDC_AZIDE                       1110
#define IDC_TRIG_ENB                    1110
#define IDC_CLOROX                      1111
#define IDC_TRIG_ENC                    1111
#define IDC_BEADS                       1112
#define IDC_END                         1112
#define IDC_TRIG_ENA2                   1112
#define IDC_ADJUST_FOCUS                1113
#define IDC_PGA_COMBO                   1113
#define IDC_TRIG_ENA3                   1113
#define IDC_AltPort                     1113
#define IDC_FILENAME                    1114
#define IDC_TRIG_ENB2                   1114
#define IDC_NormPort                    1114
#define IDC_PUMP_VOLTS_LABEL            1115
#define IDC_CURRENT_SYRINGE             1115
#define IDC_SYRINGE_SPIN                1116
#define IDC_TRIG_ENC2                   1116
#define IDC_PGA_COMBO2                  1117
#define IDC_ALT_LABEL1                  1118
#define IDC_ALT_LABEL2                  1119
#define IDC_ALT_LABEL3                  1120
#define IDC_ALT_LABEL4                  1121
#define IDC_ALT_LABEL5                  1122
#define IDC_ALT_LABEL6                  1123
#define IDC_ALT_LABEL7                  1124
#define IDC_ALT_GROUP                   1125
#define IDC_ADC_COMBO                   1126
#define IDC_BEADSVOL                    1127
#define IDC_ALT                         1128
#define IDC_PRIMPORT_VALVE              1128
#define IDC_RUN_SAMPLE_FAST             1129
#define IDC_SECPORT_VALVE               1129
#define IDC_Vol2skip                    1130
#define IDC_Vol2skipALT                 1131
#define IDC_SmplPortTxt                 1133
#define IDC_SmplPortTxt2                1134
#define IDC_AXMAX_LABEL                 1134
#define IDC_AXMAX_BOX                   1135
#define IDC_AXMAX_LABEL2                1136
#define IDC_STAINTIME                   1136
#define IDC_AXMAX_BOX2                  1137
#define IDC_ACQSTARTTIMEOUT_LABEL       1137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1137
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
